version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      fontawesome:
        patterns:
          - "@fortawesome*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "prop-types"
      tippy-js:
        patterns:
          - "tippy.js"
          - "@tippyjs*"
      babel:
        patterns:
          - "@babel*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss*"
      vite:
        patterns:
          - "vite"
          - "@vitejs*"
          - "vite-*"

