version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      fontawesome:
        patterns:
          - "@fortawesome/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "prop-types"
      mantine:
        patterns:
          - "@mantine/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
      types:
        patterns:
          - "@types/*"
      vite:
        patterns:
          - "vite"
          - "@vitejs*"
          - "vite-*"

